Replace - with _ in kernel configs

diff --git a/sbupdate b/sbupdate
--- a/sbupdate
+++ b/sbupdate
@@ -87,7 +87,7 @@ if [[ -t 1 ]]; then
 fi
 
 # shellcheck disable=SC1091,SC2016 source=sbupdate.conf
-. <(sed '/^KERNELS=/a declare -A "${KERNELS[@]}"' "$_f_config") || die "Failed to read config file '%s'" "$_f_config"
+. <(sed '/^KERNELS=/a declare -A "${KERNELS[@]//-/_}"' "$_f_config") || die "Failed to read config file '%s'" "$_f_config"
 
 [[ -d "$KEY_DIR" ]] || die "KEY_DIR '%s' doesn't exist or isn't a directory" "$KEY_DIR"
 
@@ -133,7 +133,7 @@ _f_initramfs="$2"
 
 set -eu
 
-declare -n _config="$_kernel"
+declare -n _config="${_kernel//-/_}"
 
 if [[ "$_f_initramfs" == *-fallback.img ]]; then
     _fallback=1
